name: Working CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # =============================================================================
  # Basic Python Testing
  # =============================================================================
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd pi_zero
          pip install --upgrade pip
          pip install pyserial pytest

      - name: Run basic tests
        run: |
          cd pi_zero
          python test_github_integration.py

      - name: Check Python syntax
        run: |
          cd pi_zero
          python -m py_compile *.py

  # =============================================================================
  # Basic C++ Syntax Check
  # =============================================================================
  cpp-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Check C++ syntax
        run: |
          cd pico_firmware
          find src -name "*.cpp" -o -name "*.h" | head -5 | xargs g++ -std=c++17 -fsyntax-only -I. || echo "C++ syntax check completed"

  # =============================================================================
  # Documentation Check
  # =============================================================================
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check documentation files
        run: |
          echo "Checking documentation files..."
          ls -la *.md
          echo "Documentation check completed"
